app = "tapticket"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[build.args]
  NEXT_PUBLIC_SUPABASE_URL = "https://mlvbzkpccuyiwisnbaie.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_NaxoAwyzHpjsBFEgYIUADg_R-lfomMf"
  NEXT_PUBLIC_SITE_URL = "https://tapticket.es"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
